name: Deploy Backend to o2switch

on:
  push:
    branches: [ main ]  # Change to your main branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Deploy back-end to o2switch
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /home/sesa3874/api/
          exclude: |
            node_modules/**
            .git/**
            .github/**
            .env.example
            
      - name: Restart Node.js application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          key_passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          script: |
            source /home/sesa3874/nodevenv/api/16/bin/activate
            cd /home/sesa3874/api
            npm install --production
            passenger-config restart-app /home/sesa3874/api