name: Deploy Backend to o2switch

on:
  push:
    branches: [ main ]  # Change to your main branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build preTriggerScript for restarting
        run: |
          echo "#!/bin/bash" > restart.sh
          echo "source /home/sesa3874/nodevenv/api/18/bin/activate" >> restart.sh
          echo "cd /home/sesa3874/api" >> restart.sh
          echo "npm install --production" >> restart.sh
          echo "passenger-config restart-app /home/sesa3874/api" >> restart.sh
          chmod +x restart.sh
        
      - name: Deploy back-end to o2switch via SFTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /home/sesa3874/api/
          exclude: |
            node_modules/**
            .git/**
            .github/**
            .env.example
          # Send the restart script to be executed by cron
          include: |
            restart.sh